#system-ghc: true
resolver: ghc-9.2.8

extra-deps:
- case-insensitive-1.2.1.0
- parser-combinators-1.3.0
- scientific-0.3.7.0
- hashable-1.4.2.0
- integer-logarithms-1.0.3.1
- primitive-0.8.0.0
- base-orphans-0.9.0
- data-array-byte-0.1.0.1
- megaparsec-9.3.0
- stopwatch-0.1.0.6
- clock-0.8.3
- ansi-terminal-0.11.4
- colour-2.3.6
- filepath-1.4.100.3
- bytestring-0.11.4.0
- binary-0.8.9.1
- text-2.0.2
- random-1.2.1.1
- splitmix-0.1.0.4
- directory-1.3.8.1
- unix-2.8.1.1
- monadlist-0.0.2
- network-3.1.2.9
